apiVersion: apps/v1
kind: Deployment
metadata:
  name: hasher
  labels:
    servicename: hasher
{{ include "dockercoins-all-service.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      servicename: hasher
{{ include "dockercoins-all-service.labels" . | indent 6 }}
  template:
    metadata:
      labels:
        servicename: hasher
{{ include "dockercoins-all-service.labels" . | indent 8 }}
    spec:
      containers:
        - name: hasher
          image: {{ .Values.image.registry }}/hasher:0.1
          imagePullPolicy: IfNotPresent
          env:
          - name: PROJECT_NAME
            value: "dockercoins"
          - name: ENVIRONMENT
            value: {{ .Release.Namespace }}
          - name: SERVICE_NAME
            value: hasher
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
