apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: webui
  labels:
    servicename: webui
{{ include "dockercoins-all-service.labels" . | indent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    - host: webui.192.168.56.6.nip.io
      http:
        paths:
        - backend:
            serviceName: webui
            servicePort: 80
