apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    servicename: redis
{{ include "dockercoins-all-service.labels" . | indent 4 }}
spec:
  type: ExternalName
  externalName: 192.168.56.6.nip.io
  selector:
    servicename: redis