apiVersion: v1
kind: Service
metadata:
  name: webui
  labels:
    servicename: webui
{{ include "dockercoins-all-service.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: service-port
  selector:
    servicename: webui
