apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  labels:
    servicename: worker
{{ include "dockercoins-all-service.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      servicename: worker
{{ include "dockercoins-all-service.labels" . | indent 6 }}
  template:
    metadata:
      labels:
        servicename: worker
{{ include "dockercoins-all-service.labels" . | indent 8 }}
    spec:
      containers:
        - name: worker
          image: 10.104.15.174:5000/worker:0.1
          imagePullPolicy: IfNotPresent
          env:
          - name: PROJECT_NAME
            value: "dockercoins"
          - name: ENVIRONMENT
            value: {{ .Release.Namespace }}
          - name: SERVICE_NAME
            value: worker
          livenessProbe:
            exec:
              command:
              - ps
              - aux | grep python | grep -v grep
          readinessProbe:
            exec:
              command:
              - ps
              - aux | grep python | grep -v grep
