{{- if .Values.ingress.enabled -}}
{{- $fullName := include "dockercoins-single-service.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
{{ include "dockercoins-single-service.labels" . | indent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    - host: {{.Release.Namespace}}-webui.192.168.56.6.nip.io
      http:
        paths:
        - backend:
            serviceName: {{ .Values.servicename }}
            servicePort: 80
{{- end }}
