# Default values for dockercoins-single-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  registry: 10.104.15.174:5000

ingress:
  enabled: false
